version: '3'
services:
  mysql_local:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'engage'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_local_data:/var/lib/mysql
volumes:
  mysql_local_data:
