"use strict";
exports.__esModule = true;
require("dotenv").config();
var express_1 = require("express");
var body_parser_1 = require("body-parser");
var app = (0, express_1["default"])();
app.use((0, body_parser_1.json)());
app.use((0, body_parser_1.urlencoded)({ extended: true }));
require("./routes/company.routes")(app);
require("./routes/employee.routes")(app);
require("./routes/login.route")(app);
require("./routes/welcome.route")(app);
exports["default"] = app;
